### ISSUE TITLE
Won't complete initializing step

### ISSUE THREAD

**Issue by ChromoX** [rawmind0/alpine-zk#2]
I deployed Zookeeper using the Docker catalog. Zookeeper refuses to start, and gives an error about not finding a ```myid``` file in the entered data directory I specified via the Catalog config screen.

**Comment by rawmind0** [comment]
Could you please try with new releases??

**Comment by ChromoX** [comment]
I ended up building my own Zookeeper docker images.
Thanks for your work though!
